### ISSUE TITLE
A couple of suggestions

### ISSUE THREAD

**Issue by EddoWagt** [GnomeSnapExtensions/gSnap#1]
Hey I just installed this extension and so far I like it, but I think there's a few points that could use some changes.
First of all I'd like to use a modifier like shift for the popup, similar to FancyZones, I don't always want zone snapping so that would be a useful addition imo.
Secondly I want to disable/change the tabs that appear at the top, I think the idea is great, but they take up too much space imo. Maybe this can be disabled or have a popup with another modifier, I don't really know what would work best.
And finally the zones are a bit difficult to distinguish, I think the edges need to be a bit brighter.
Apart from these 3 things I think the extension is really good!

**Comment by mtbhuskies** [comment]
I agree with  the above. 

I would also like to have zones between monitors. In  FancyZones, I can set zones for my horizontal and zones for my vertical monitor independently. This would be a great feature to add. This is the extension I've been looking for!

**Comment by Yan-Solo** [comment]
The first point would make this extension perfect for me. I'm looking at the source code but sadly I'm not a developer.
I think I added a modifier to the schema but I'm not yet sure on how to make it check for the modifier being pressed before activatin the preview during the dragging of a window,

**Comment by MattyGWS** [comment]
Just popping in to say the same thing as OP's first point. in windows I hold shift down when i want to move and resize windows without snapping them. This extension would be perfect with such a function!

Other than that, amazing work thank you... I have a 5120x1440 monitor and this is just what I needed for linux

**Comment by ViolentSempie** [comment]
> Just popping in to say the same thing as OP's first point. in windows I hold shift down when i want to move and resize windows without snapping them. This extension would be perfect with such a function!
> 
> Other than that, amazing work thank you... I have a 5120x1440 monitor and this is just what I needed for linux
> 
> EDIT: would buy a coffee for the developer that adds the functionality I mentioned :D

Hey, I had the same issue as OP and you and decided to make a little fork that adds this functionality. You can check it here: https://github.com/ViolentSempie/gSnap

It uses control as modifier as shift already does some stuff with window dragging as a default. I might add more functionality like choosing which modifier you want to use, reverse modifier (hold to not snap) and more later but this is a first draft :).

**Comment by meronz** [comment]
Why don't you open a PR here? I'll be happy to review it and mainline this useful feature!

**Comment by ViolentSempie** [comment]
Sure I can open a PR if you want :).

**Comment by meronz** [comment]
I also have fixed the last suggestion (#29), the one regarding zones color. Is in the main branch (official release will come when we have some more features/fixes to release)

**Comment by meronz** [comment]
I will close this issue as every problem addressed has been fixed. Feel free to open a new one for new suggestions :)
