### ISSUE TITLE
Publish new version to extensions.gnome.org

### ISSUE THREAD

**Issue by asteinba** [GnomeSnapExtensions/gSnap#20]
See the title :-). It seems that the master branch contains multi monitor support and better area detection. I installed from source. Very cool features that are worth to be released to extensions.gnome.org. Version in metadata.json is still 6 as in the gnome store. Are you collecting features for a new version or how are you doing the releases?

**Comment by meronz** [comment]
Hi Micah, I can do it. As a matter of fact, I'm still working on it in my spare time. I've got planned some big features, but it takes time

**Comment by meronz** [comment]
Another way of doing this might be moving the project under a Github organization and having multiple maintainers. Is it doable?

**Comment by micahosborne** [comment]
@meronz great. What should we call the organization. Also i'll need your gnome extensions (the store where you install the extensiion) to transfer it to another account.

**Comment by meronz** [comment]
I think _gSnap_ as the organization name is the safest bet!

I also sent you the infos privately on the mail account indicated on your GitHub profile 😉

**Comment by micahosborne** [comment]
gSnap is already taken, i'm at a loss on what to use haha.

**Comment by micahosborne** [comment]
I just made it longer, i sent you and invite to the org

**Comment by micahosborne** [comment]
Ok gsnap is now under the new organization

**Comment by meronz** [comment]
Cool! Fine for the name and thanks for merging the PR. When Gnome approves the request for change, I’ll submit the new release for review

**Comment by meronz** [comment]
Version 9 has been released!
