### ISSUE TITLE
Multi monitor support not working with displaylink monitors

### ISSUE THREAD

**Issue by aaronrancsik** [GnomeSnapExtensions/gSnap#25]
I have a displaylink docker where I connect two monitors. It is handled as one big monitor.

**Comment by meronz** [comment]
I'm not familiar with this kind of device.. If I understood correctly and only one monitor is presented to the OS, there's not much the extension can do to support this scenario. If you open something like the Gnome settings, how many screens do you see?

**Comment by aaronrancsik** [comment]
Thanks for the reply! It's a bit different than a regular monitors connected directly to gpu, it's use virtual displays: https://github.com/DisplayLink/evdi

But the OS is aware of the different displays in gnome control center I can see the two monitor.

**Comment by meronz** [comment]
I'm not familiar with the device in question nor do I have access to this setup. If you're up for it, I could guide you into troubleshooting and fixing the problem yourself.

You can start by getting the logs:
- Enable them in the gSnap extension settings
- Get them by running `journalctl --follow /usr/bin/gnome-shell | grep "gSnap"`.

**Comment by aaronrancsik** [comment]
I'm happy to help debug this issue. Since I opened this issue  I was not using this extension. Now I installed again to debug but now gSnap is correctly detected my two monitors :) I don't change nothing just regular updates including kernel. I will start to use gSnap now. If I encounter the issue again I will comment here the logs. Thanks for the help anyway!

**Comment by meronz** [comment]
Oh maybe you were just using the old version, which did not have multi-monitor support at all! I'm closing the issue now, feel free to reopen it if you encounter any issue.
