### ISSUE TITLE
When switchng workspace screen turns dim

### ISSUE THREAD

**Issue by iceaway** [GnomeSnapExtensions/gSnap#31]
Thanks for a great extension! I have discovered one minor issue. When I change workspace, the entire screen goes 'dim', sort of how it looks when you are trying to snap a window. When this happens, I can "wiggle" the window title bar of a window and it will go away. Any ideas what could be causing this?

**Comment by meronz** [comment]
This should be fixed now, it was happening only when Tabs were disabled. Please try with the main branch and let me know if it solves the problem for you!

**Comment by iceaway** [comment]
Brilliant, works like a charm! Thanks a lot for the quick fix!
