### ISSUE TITLE
Feature Request: Zone size configuration with pixels

### ISSUE THREAD

**Issue by LarsJaeger** [GnomeSnapExtensions/gSnap#35]
Make Zones configurable with pixel sizes. Let's say for example I have my 3440x1440 monitor and want a centered main window with a resolution of 1920x1440. This is really hard to do with the percentages in the zone configuration and would be nice if instead of a percentage it would be possible to set explicit pixel sizes for the zones.

Btw: I really like your project, thank you for your work (although it is currently unusable for me due to #34 )

**Comment by EddoWagt** [comment]
Agreed, it also makes no sense to show the sizes in percentages with like 10 decimals accuracy, pixels would be much better

**Comment by meronz** [comment]
As a great improvement this might be, I currently do not have time to work on this. But thanks for opening the issue!

**Comment by EddoWagt** [comment]
Perhaps decreasing the amount of decimals is possible? Not sure how hard that would be to code. I think 2 decimal points would be plenty

**Comment by meronz** [comment]
What i could do is to show the widget size in pixels when editing the zones. Inputing the zone size in pixels is not possible without a good rewrite of the ZoneEditor class and how widgets are drawn on the screen. Feel free to open another issue if this is not sufficient for you.
