### ISSUE TITLE
Window positions reset on external monitor

### ISSUE THREAD

**Issue by dhelonious** [GnomeSnapExtensions/gSnap#43]
All windows are moved to the default column (the middle one in my 3 column layout) after I unlock my system after it went into hibernate. I assume that this happens when my external HDMI display gets disconnected.

Unfortunately, other extensions which should resolve this (i. e. Window State Manager, Smart Auto Move, ...) do not work with gSnap. It imagine that this could be resolved if gSnap could sort windows into columns based on the position at which a window opens?

**Comment by pellle87** [comment]
Im experiencing kinda the same problem. when my monitors go to sleep, some windows remains and 1 or to totally forgets.
I've also noticed that sometimes my 49" screen shows up as monitor 0 and sometimes monitor 1

**Comment by meronz** [comment]
This should be solved by the latest release (23). Please check if it solves the problem for you, and feel free to reopen the issue if it does not. Remember to enable and attach logs when opening issues, you can find out how to do that in the README.
