### ISSUE TITLE
Tray icon does not maintain its spacing

### ISSUE THREAD

**Issue by SuperJC710e** [GnomeSnapExtensions/gSnap#44]
First of all, thanks for the extension. It really helps when I need to flip between my Windows work machine (with Fancy Zones) and my Linux machine!

One issue I've noted is that the tray icon does not maintain it's spacing when I'm using the [Status Area Horizontal Spacing](https://gitlab.com/p91paul/status-area-horizontal-spacing-gnome-shell-extension) extension. I haven't noticed any other icons with this issue. Is there a way to fix that?

[![With Extension](https://imgur.com/19Xs06v.png)](https://imgur.com/a/eZfIRCH)

[![Without Extension](https://i.imgur.com/77fVsQi.png)](https://imgur.com/a/eZfIRCH)

TIA!

**Comment by meronz** [comment]
I will try to reproduce and fix it in the holidays. Hopefully I will have some time to spare :D

**Comment by SuperJC710e** [comment]
Thanks @meronz, much appreciated! :)

**Comment by meronz** [comment]
Closed in the linked PR. You will have to wait for the next release, as I plan to release as many fixes as possible in a single release.

**Comment by SuperJC710e** [comment]
> Closed in the linked PR. You will have to wait for the next release, as I plan to release as many fixes as possible in a single release.

Thanks! Just got the update today, and it's looking good. The icon maintains it's spacing, also it's not dimmed like before! Great job! :+1:

**Comment by meronz** [comment]
Thanks. Wish you a happy new year!
