### ISSUE TITLE
Extension broken when installed in read-only directory

### ISSUE THREAD

**Issue by elizagamedev** [GnomeSnapExtensions/gSnap#45]
Some Linux distros package gSnap upstream, like [NixOS](https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/desktops/gnome/extensions/buildGnomeExtension.nix). Unfortunately, gSnap assumes that its own directory is user-writable, which is not the case when installing as a system package. In such cases, an error like the following is thrown shortly after enabling gSnap:

```
GLib.FileError: Failed to create file “/etc/profiles/per-user/eliza/share/gnome-shell/extensions/gSnap@micahosborne/layouts.json.UFBZW1”: Read-only file system
```

Perhaps instead of storing data in this directory, the next version of gSnap could instead store it somewhere in `$XDG_CONFIG_DIR` with some backwards-compatibility glue?

**Comment by meronz** [comment]
Mmh nice catch. This is something that should definitively be implemented.

**Comment by meronz** [comment]
@elizagamedev I opened a PR with the requested changes. I think it was an error to store the layouts.json file in the extension directory anyway, so I changed it in favor of ~/.config, or whatever the user_config_dir is. Could you test the PR to see if it works on your side? I'm also downloading an ISO of NixOS (which I've never used before) to test it, but a test from an experienced NixOS user would be best.

In the future, I'd like to store everything in dconf as it is cleaner and avoids these sorts of problems.

**Comment by meronz** [comment]
I'll close the issue. Feel free to reopen it if this does not solve the problem.

**Comment by elizagamedev** [comment]
Thank you for the quick fix! I'll try this out on Nix.
