### ISSUE TITLE
keyboard shortcuts to move windows around  / or tell gnome about my gSnap zones

### ISSUE THREAD

**Issue by petersenna** [GnomeSnapExtensions/gSnap#57]
Hi,

I would like to use Super+arrow keys to move windows across my zones. Currently super + left/right are captured by Gnome for placing the window on 50% of the screen, left of right. There is another similar request [here](https://github.com/GnomeSnapExtensions/gSnap/issues/6).

I have little clue about how gnome extensions work, and the amount of work required to implement this keyboard shortcuts, but if there are no major blocker to get this working, I want to give it a try. Can I get some pointers on how to do it? I am happy to move this discussion to email or other channel if that would help.

Thank you!

**Comment by meronz** [comment]
Sure thing! 

Before you start experimenting with the code, I'd suggest you read the official [docs](https://gjs.guide/) on how Gnome Extensions work and get comfortable with the Gnome inspector (ALT-F2, type `lg`).

To implement new keybindings you can follow how other keybindings are implemented (such as `PRESET_RESIZE_1`). 
Roughly speaking, this means:
- Adding the new keybinding settings in the `schemas/org.gnome.shell.extensions.gsnap.gschema.xml` file. Keybindings are handled via settings to allow users to change them.
- Compile the schema (`schemas/README.md`)
- Add labels for these new settings in the `prefs_builder.ts`
  ```javascript
    const pretty_names = {
        [SETTINGS.PRESET_RESIZE_1]: 'Layout 1',
        // add yours...
   }
  ```
- Handle them in the `app.ts`
  ```javascript
    const key_bindings_presets: Bindings = new Map([
        [SETTINGS.PRESET_RESIZE_1, () => {
            globalApp.setLayout(0);
        }],
        // add yours...
  ```


To implement it, the first thing that comes into my mind is
- In `app.ts` create some methods (follow how `setLayout` has been done)
- Look up the currently focused window (`monitors.ts` exports the `getWindowsOfMonitor` function that returns an array of `Window`s, just call `has_focus()`.
- Get the position of said window
- By calling `getWorkspaceMonitorCurrentLayoutOrDefault`, get the various zones that compose a layout, and comparing the various sizes/positions, get the zone that is interesting for you (up/down/left/right).
- Move the window to said zone:
  ```javascript
    win.move_frame(true, selection.x, selection.y);
    win.move_resize_frame(true, selection.x, selection.y, selection.width, selection.height);
  ```

Experiment with it thoroughly and remember to test it on both Xorg and Wayland! :)

**Comment by meronz** [comment]
Well I had the time to implement it. Can you test if it works for your use case? I'll wait before merging it.

**Comment by petersenna** [comment]
> Well I had the time to implement it. Can you test if it works for your use case? I'll wait before merging it.

First of all, thank you very much for looking into this! I am using Fedora 37, and I tested on both X and Wayland, I also tested with two grid configurations.

Only Super + left works. Sometimes Super + down moves back, but not very often. I also noticed that once the window reaches the leftmost zone, it stops there. I guess it would be desirable to cycle trough all zones, so after the leftmost zone, the window would jump to the rightmost zone.

After using it I noticed that Super+up and Super+down may also be needed for switching between zones that are on top of each other. And that may impose a problem as these shortcuts are useful to maximize and minimize windows.

So what do you think of using Super+Ctrl+Arrows instead?

**Comment by petersenna** [comment]
After this patch, all arrows work fine, but I do not know why. My hypothesis is because the size of the gnome-terminal window varies in steps to match font size, but I have no idea.

```

diff --git a/src/extension/editor.ts b/src/extension/editor.ts
index 3a117d6..894b372 100644
--- a/src/extension/editor.ts
+++ b/src/extension/editor.ts
@@ -722,13 +722,13 @@ export class ZoneDisplay extends ZoneGroup {
                 y = frameRect.y - (1 + this.margin);
                 break;
             case MoveDirection.Down:
-                y = frameRect.y + frameRect.height + (1 + this.margin);
+                y = frameRect.y + frameRect.height + this.margin + 50;
                 break;
             case MoveDirection.Left:
                 x = frameRect.x - (1 + this.margin);
                 break;
             case MoveDirection.Right:
-                x = frameRect.x + frameRect.width + (1 + this.margin);
+                x = frameRect.x + frameRect.width + this.margin + 5;
                 break;
         }

```

**Comment by meronz** [comment]
> After using it I noticed that Super+up and Super+down may also be needed for switching between zones that are on top of each other. And that may impose a problem as these shortcuts are useful to maximize and minimize windows.
> So what do you think of using Super+Ctrl+Arrows instead?

Super+Ctrl+Arrows is already used by the gnome integrated window "tiling" (the left/right halves of the screen and maximize) and I don't know if we can replace those keybindings easily. CTRL+ALT+Arrows maybe?

> I noticed that increasing the width of the window before trying to move it would make the right arrow work, and the same for height and down arrow.

I cannot reproduce the problem you are encountering. I tried with margins up to 16px. What settings, display size, applications are you using? Are you using window scaling?

**Comment by meronz** [comment]
Hey @petersenna, are you still encountering the issues you described?

**Comment by meronz** [comment]
I've found the problem and fixed it.

**Comment by petersenna** [comment]
@meronz I am sorry but I am not able to test it. Super sorry.
