### ISSUE TITLE
error loading extension

### ISSUE THREAD

**Issue by Hbodor** [GnomeSnapExtensions/gSnap#65]
I am trying to install the extension in a Debian 10 machine (Gnome 3.30.2). I follow the gsnap developpement procedure, the installation goes fine, but when I try to activate the extension through "Tweaks", I have a warning sign "Error loading extension" near gsnap, and when I click the settings button of the extension, I have the following error message :

`
TypeError: imports.misc.extensionUtils.getSettings is not a function

Stack trace:
  basics_tab@/home/user/.local/share/gnome-shell/extensions/gSnap@micahosborne/prefs.js:140:24
  build@/home/user/.local/share/gnome-shell/extensions/gSnap@micahosborne/prefs.js:214:9
  buildPrefsWidget@/home/user/.local/share/gnome-shell/extensions/gSnap@micahosborne/prefs.js:307:12
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:83:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43

`

Can please someone help me figure out what is the issue ?

**Comment by Hbodor** [comment]
The journalctl outrputs the following : 

`
Jun 01 17:01:59 user1234 gnome-shell[9963]: Extension "gSnap@micahosborne" had error: TypeError: GObject.registerClass() used with invalid base class (is ModalDialog)

Jun 01 17:01:59 user1234 gnome-shell[9963]: Extension "gSnap@micahosborne" had error: TypeError: GObject.registerClass() used with invalid base class (is ModalDialog)
Jun 01 17:15:39 user1234 gnome-shell[13632]: Extension "gSnap@micahosborne" had error: TypeError: GObject.registerClass() used with invalid base class (is ModalDialog)
Jun 01 18:00:27 user1234 org.gnome.Shell.desktop[13632]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x220002c (gSnap)
Jun 01 18:00:27 user1234 org.gnome.Shell.desktop[13632]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2200096 (gSnap)
Jun 01 18:00:28 user1234 org.gnome.Shell.desktop[13632]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x22000e8 (gSnap)
Jun 01 18:11:38 user1234 gnome-shell[13632]: JS WARNING: [/home/e44106/.local/share/gnome-shell/extensions/gSnap@micahosborne/extension.js 897]: mistyped ; after conditional?
Jun 01 18:11:38 user1234 gnome-shell[13632]: Extension "gSnap@micahosborne" had error: TypeError: GObject.registerClass() used with invalid base class (is ModalDialog)
`

**Comment by meronz** [comment]
The extension is not compatible with Gnome < 40.
