### ISSUE TITLE
Howto install Gsnap on Ubuntu 23.04

### ISSUE THREAD

**Issue by tommiedepommie** [GnomeSnapExtensions/gSnap#67]
Hello,

I'm a Linux Mint user for several years and because I bought a bigger monitor (43"), I installed Ubuntu 22.10 while I want to make use of Gsnap.
I updated to 23.04 but the extension didn't worked any more.
Hoe can I install the Gsnap extension on Ubuntu 23.04 because using the extension page doesn't work (yet).
Thank you very kindly.

Tom

**Comment by juliancarrivick** [comment]
I think a new version needs to be released, #59 has been merged which adds support for Gnome 44 (which is what comes with 23.04), but this isn't reflected in what's available on the extension store.

**Comment by meronz** [comment]
I've pushed the release [releases/14](https://extensions.gnome.org/review/43461) to extensions.gnome.org. We are waiting for the review :)

**Comment by meronz** [comment]
Extension has been released, enjoy!
