### ISSUE TITLE
Changing workspaces un-minimises windows

### ISSUE THREAD

**Issue by bmaupin** [GnomeSnapExtensions/gSnap#68]
I'm using gSnap version 14 with Gnome Shell version 42 on Ubuntu 22.

If I minimise a window, change to another workspace, then switch back to the workspace where I minimised the window, the window is no longer minimised.

**Comment by normanr** [comment]
It also happens I lock & unlock.

**Comment by meronz** [comment]
I opened a PR, let me know if it fixes the problem for you.

**Comment by meronz** [comment]
Great, I'll merge it then!
