### ISSUE TITLE
Gnome 45 compatibility

### ISSUE THREAD

**Issue by meronz** [GnomeSnapExtensions/gSnap#74]
Gnome 45 breaks retro-compatibility with older versions by moving to ESM modules.
https://gjs.guide/extensions/upgrading/gnome-shell-45.html

A lot of stuff broke and maintaining compatibility is too much work.
Stuff that broke/needs change
- [x] Extension loading, basic functionality
- [x] Preferences
  - [x] Make the preferences window work with LibAdwatia
  - [ ] Remove any reference to Gtk: this means rewriting the keybindings section.
- [x] Animations are not working anymore
  - I had no 3D acceleration for my VM 🤦

I also need help doing extensive tests on the whole extension functionality set. Anyone is welcome to contribute. I'm working on the [issues/74-gnome45support](https://github.com/GnomeSnapExtensions/gSnap/tree/issues/74-gnome45support) branch.

**Comment by peterloeffler** [comment]
As gSnap is an (if not THE) essential part of my daily workflow I would appreciate this very much!
Fedora 39 is coming soon ;-)

**Comment by meronz** [comment]
Yea, I have already started working on it but i was waiting for Fedora 39 beta to be released.

**Comment by meronz** [comment]
I attempted to make a single codebase work with both pre-45 and 45 GNOME releases, but it's too much work since *a lot* of stuff broke.
I decided to branch out the old releases (Gnome 40 to 44 [here](https://github.com/GnomeSnapExtensions/gSnap/tree/40-44)) and keep working on main for Gnome 45 and (hopefully onwards). This means that older releases won't see much new work as it is very difficult for me to handle both branches.

**Comment by korvahannu** [comment]
How is the work on GNOME 45 compatibility going? I would love to help, but I have no experience on scripting gnome extensions

**Comment by KylerJohnsonDev** [comment]
@meronz Thanks so much for your work on this. I have two young kids (one if 3 months old) so I'm short on time to contribute with code, but I'd love to contribute a little something monetarily. Do you have a patreon or a "buy me a coffee" or something like that? This such a critical piece to my workflow that I really want to give back somehow.

**Comment by meronz** [comment]
Thank you but it is not necessary! I too have little time on my hands so I do what I can, with or without monetary compensations (which I do not need nor want) - but thanks for wanting to help, I appreciate that.

The project has a "buy me a coffee" button on the README page for the original creator of the extension @micahosborne , tagging to see if maybe he can do something to help. 


That said, the branch mostly works (apart from some non-essential functionality). If I don't release gSnap before your preferred distro comes out with Gnome 45, you could still build it and use it.

**Comment by KylerJohnsonDev** [comment]
Thanks! 

Many coffees bought for @micahosborne. Open source work like this doesn't get enough appreciation.

**Comment by KylerJohnsonDev** [comment]
Is most of the remaining work really just updating imports? Or is there more to it than that? I'm going to try to carve out some time to help, but I can't make any guarantees.

**Comment by meronz** [comment]
> Is most of the remaining work really just updating imports?

This has already been done! You can check progress by reading the description of the issue (I will keep it updated).

**Comment by meronz** [comment]
This should be done! We have Gnome 45 compatibility :D

**Comment by peterloeffler** [comment]
Awesome! Thank you so much!
Tested it on openSUSE Tumbleweed for now.
Works perfectly fine for me.
