### ISSUE TITLE
Unable to use "Create New Layout" or "Rename" options after upgrading to Gnome 45. 

### ISSUE THREAD

**Issue by danshryock** [GnomeSnapExtensions/gSnap#78]
After upgrading to Gnome 45, I can't rename or create a layout through the user interface.

When I click on either of those menu options, nothing happens.

I'm not familiar with Gnome development, extensions, or APIs, so I'm not sure if this is an upstream bug somewhere in Gnome, or if it is just a breaking change in the ModalDialog API.

I enabled debug mode, and captured the trace from the console, and here are the messages I am seeing:

```
JS ERROR: TypeError: super.contentLayout is undefined
_init@file:///home/username/.local/share/gnome-shell/extensions/gSnap@micahosborne/extension.js:1385:9
ModalDialog@resource:///org/gnome/shell/ui/modalDialog.js:37:4
EntryDialogClass@file:///home/username/.local/share/gnome-shell/extensions/gSnap@micahosborne/extension.js:1363:9
reloadMenu/<@file:///home/username/.local/share/gnome-shell/extensions/gSnap@micahosborne/extension.js:2109:26
activate@resource:///org/gnome/shell/ui/popupMenu.js:194:14
_init/<@resource:///org/gnome/shell/ui/popupMenu.js:111:24
@resource:///org/gnome/shell/ui/init.js:21:20
```

I looked at line 1385 of extension.js and found: `super.contentLayout.add(box);`

I believe original source for that line is here:
https://github.com/GnomeSnapExtensions/gSnap/blob/6fffcdc5fae908b50591fd8130ca093c3e9dd960/src/extension/editor.ts#L1114

I also get this message in the log, but I'm not sure if it is related:
```
Attempting to add actor of type 'Gjs_ui_popupMenu_PopupMenuItem' to a container of type 'StBoxLayout', but the actor has already a parent of type 'StBoxLayout'.
```

**Comment by meronz** [comment]
Oh, I did not catch this one! I'll make space this weekend to reproduce and fix it :)

**Comment by ValdoTheCoder** [comment]
Can confirm that bug still persists on Ubuntu 23.10 and Gnome 45.2.

However easy workaround to create and edit layout is simply by directly editing `layouts.json` file located `.config/gSnap/`.

Funny fact: Editing JSON is easier than using an interface for that.
