### ISSUE TITLE
Update for gnome 46

### ISSUE THREAD

**Issue by nnamua** [GnomeSnapExtensions/gSnap#82]
Hey, thanks for the great extension!
Really happy so far, and I was very unhappy when I had to resort to the default snapping behaviour when i updated to gnome 46. Fortunately, I don't think anything broke (I have just changed the version number in the metadata, and everything works so far at least on my end).

**Comment by perinm** [comment]
Bump! Specially with Ubuntu 24.04 right on the corner

**Comment by ShoQue92** [comment]
Bump! I am a happy user myself as well. Would love to use it under 24.04.

**Comment by perinm** [comment]
Just built on ubuntu 24.04 and also worked normally!
